export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const RESET_USER = "RESET_USER";

export const GET_USER_REPORTS_REQUEST = "GET_USER_REPORTS_REQUEST";
export const GET_USER_REPORTS_SUCCESS = "GET_USER_REPORTS_SUCCESS";

export const GET_NEARBY_REPORTS_REQUEST = "GET_NEARBY_REPORTS_REQUEST";
export const GET_NEARBY_REPORTS_SUCCESS = "GET_NEARBY_REPORTS_SUCCESS";

export const GET_HELP_REPORTS_REQUEST = "GET_HELP_REPORTS_REQUEST";
export const GET_HELP_REPORTS_SUCCESS = "GET_HELP_REPORTS_SUCCESS";

export const GET_ZONE_REPORTS_REQUEST = "GET_ZONE_REPORTS_REQUEST";
export const GET_ZONE_REPORTS_SUCCESS = "GET_ZONE_REPORTS_SUCCESS";

export const UPDATE_HELP_REPORT_REQUEST = "UPDATE_HELP_REPORT_REQUEST";
export const UPDATE_HELP_REPORT_SUCCESS = "UPDATE_HELP_REPORT_SUCCESS";

export const UPDATE_FOUND_CHILD_REQUEST = "UPDATE_FOUND_CHILD_REQUEST";
export const UPDATE_FOUND_CHILD_SUCCESS = "UPDATE_FOUND_CHILD_SUCCESS";

export const ADD_USER_REPORTS_REQUEST = "ADD_USER_REPORTS_REQUEST";
export const ADD_USER_REPORTS_SUCCESS = "ADD_USER_REPORTS_SUCCESS";

export const ADD_HELP_REPORTS_REQUEST = "ADD_HELP_REPORTS_REQUEST";
export const ADD_HELP_REPORTS_SUCCESS = "ADD_HELP_REPORTS_SUCCESS";

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const RESET_UPDATE_USER = "RESET_UPDATE_USER";
