export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const RESET_USER = "RESET_USER";

export const GET_USER_REPORTS_REQUEST = "GET_USER_REPORTS_REQUEST";
export const GET_USER_REPORTS_SUCCESS = "GET_USER_REPORTS_SUCCESS";

export const GET_NEARBY_REPORTS_REQUEST = "GET_NEARBY_REPORTS_REQUEST";
export const GET_NEARBY_REPORTS_SUCCESS = "GET_NEARBY_REPORTS_SUCCESS";

export const GET_ZONE_REPORTS_REQUEST = "GET_ZONE_REPORTS_REQUEST";
export const GET_ZONE_REPORTS_SUCCESS = "GET_ZONE_REPORTS_SUCCESS";

export const ADD_USER_REPORTS_REQUEST = "ADD_USER_REPORTS_REQUEST";
export const ADD_USER_REPORTS_SUCCESS = "ADD_USER_REPORTS_SUCCESS";
